server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: PhamHa220203@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "tMj8f6JGhhe0u9ZYTWqbh3ah7dBpgAgM/boSx5Orux4yXh/AInu+GhU291DDi2Xg"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds